# Generated by Django 3.1.2 on 2021-06-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_bid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='price',
            new_name='bidding',
        ),
        migrations.AddField(
            model_name='listing',
            name='price',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
